# Generated by Django 2.1.4 on 2019-02-17 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='DeckState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FieldCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('attack', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('turns_alive', models.IntegerField(default=0)),
                ('attacks_per_turn', models.IntegerField(default=1)),
                ('attacks_left', models.IntegerField(null=True)),
                ('charge', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='FieldState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.SlugField()),
                ('turn', models.IntegerField(null=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('winner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HandCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='HandState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HeroCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.IntegerField(default=0)),
                ('picture', models.ImageField(null=True, upload_to='card_pictures/')),
                ('hp', models.IntegerField(default=30)),
                ('effect', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonsterCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.IntegerField(default=0)),
                ('picture', models.ImageField(null=True, upload_to='card_pictures/')),
                ('hp', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonsterCardState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.IntegerField(default=0)),
                ('picture', models.ImageField(null=True, upload_to='card_pictures/')),
                ('hp', models.IntegerField(default=1)),
                ('attack', models.IntegerField(default=1)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.GameState')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_moving', models.BooleanField()),
                ('is_first', models.BooleanField()),
                ('hp', models.IntegerField(null=True)),
                ('mana', models.IntegerField(null=True)),
                ('max_mana', models.IntegerField(null=True)),
                ('game_state', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.GameState')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpellCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('cost', models.IntegerField(default=0)),
                ('picture', models.ImageField(null=True, upload_to='card_pictures/')),
                ('effect', models.CharField(max_length=500)),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('preferred_deck', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='game.Deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='handstate',
            name='player_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.PlayerState'),
        ),
        migrations.AddField(
            model_name='handcard',
            name='hand_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.HandState'),
        ),
        migrations.AddField(
            model_name='fieldstate',
            name='player_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.PlayerState'),
        ),
        migrations.AddField(
            model_name='fieldcard',
            name='field_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.FieldState'),
        ),
        migrations.AddField(
            model_name='deckstate',
            name='player_state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.PlayerState'),
        ),
        migrations.AddField(
            model_name='deckcard',
            name='deck_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.DeckState'),
        ),
        migrations.AddField(
            model_name='deck',
            name='monster_cards',
            field=models.ManyToManyField(blank=True, to='game.MonsterCard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='spell_cards',
            field=models.ManyToManyField(blank=True, to='game.SpellCard'),
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
